### ISSUE TITLE
How can we get in contact?

### ISSUE THREAD

**Issue by Padm59** [Duckle29/EEValue#1]
Hello,
I read your question ( https://github.com/crankyoldgit/IRremoteESP8266/issues/1436#issue-837735895 ) and I basically to the same thing. Controlling my AC with MQTT and I have a problem. How do you parse the incoming message from the Ir receiver into the actual state and how do you send it over MQTT. 

Hope you can help me with that because that's the only missing thing in my AC control.

You can email me if you want: philadm59@gmail.com

**Comment by Duckle29** [comment]
Hi, all the code for my wifi IR project is here https://github.com/Duckle29/wifir_firmware. Feel free to ask questions on that repo :)
