### ISSUE TITLE
Units and error returns

### ISSUE THREAD

**Issue by sebastianschuler** [Duckle29/EEValue#4]
Hello,

while looking for example schematics of the LM5169 DC/DC converter, I saw your question on TI E2E and liked your approch to use python to calculate all the required values. Through your name and the python import I found this repository :-)

I was having issues to recreate you calculations, since some additional arguments for units and error returns are not inside the code.
Would you be so kind to update this repo to include this?

Sebastian

**Comment by Duckle29** [comment]
Hi, yes :)

I've been meaning to get around to updating this. I have some bug-fixes too.

If you plan to use this library, be aware that I've seen some weird rounding errors in some cases, like rounding up 227 to 360 instead of 330, because it's rounding the E series exponent.

**Comment by Duckle29** [comment]
Should be there now. Hope it's useful :) https://github.com/Duckle29/EEValue/releases/tag/2.0.1

**Comment by sebastianschuler** [comment]
Hey, thanks so much for updating the library! 👍
